// ============================================================
// calibration_data.h  —  auto-generated by gen_cal_header.py
// Profile  : Anoop B A
// Date     : 20260604
// Source   : calibration_20260604.json
// Generated: 2026-06-04 12:45
//
// IMPORTANT: cal_min = OPEN hand ADC,  cal_max = CLOSE hand ADC
// For sensors where open > close, cal_min > cal_max (negative range).
// norm_finger() handles this correctly:
//   v = (val - cal_min) / (cal_max - cal_min)  [clamped 0..1]
//   → open hand always = 0.0,  close hand always = 1.0
//
// DO NOT EDIT — regenerate: python3 gen_cal_header.py
// ============================================================

#ifndef CALIBRATION_DATA_H
#define CALIBRATION_DATA_H

// Channel order: [0-4] right hand, [5-9] left hand
// Within each hand: 0=thumb, 1=index, 2=middle, 3=ring, 4=little

// CAL_MIN_DATA[i] = ADC value when hand is FULLY OPEN
static const float CAL_MIN_DATA[10] = {
    1785.83f,  // [0] R_Thumb
    2607.43f,  // [1] R_Index  // inverted sensor
    2604.70f,  // [2] R_Middle  // inverted sensor
    1242.57f,  // [3] R_Ring
    1337.93f,  // [4] R_Little
    1358.57f,  // [5] L_Thumb
    1164.23f,  // [6] L_Index
    1458.57f,  // [7] L_Middle
    2669.63f,  // [8] L_Ring  // inverted sensor
    2124.10f   // [9] L_Little  // inverted sensor
};

// CAL_MAX_DATA[i] = ADC value when hand is FULLY CLOSED (fist)
static const float CAL_MAX_DATA[10] = {
    2123.07f,  // [0] R_Thumb
    2160.07f,  // [1] R_Index
    2154.67f,  // [2] R_Middle
    2110.60f,  // [3] R_Ring
    2041.33f,  // [4] R_Little
    1646.93f,  // [5] L_Thumb
    1854.97f,  // [6] L_Index
    1782.23f,  // [7] L_Middle
    1822.83f,  // [8] L_Ring
    1831.70f   // [9] L_Little
};

#endif // CALIBRATION_DATA_H
