// =============================================================
// Smart Glove Phase 10 — Master Inference (v6 — FINAL)
// Board  : ESP32-S3 DevKitC-1 (Right Hand / Master)
// Core   : ESP32 2.0.17  (GCC 8.4 — do NOT upgrade to 3.x)
// Library: TensorFlowLite_ESP32 1.0.0
// Patches: stl_emulation.h ~386 comment out count_=other.count_;
//          move src/screen and src/bus out of src/ folder
// =============================================================
// PREPROCESSING matches live_inference.py EXACTLY:
//   1. analogRead  → EMA filter (alpha=0.25)  [all 16 channels]
//   2. EMA fingers → normalise 0-1 (cal_min/cal_max)
//   3. EMA IMU     → pass through in degrees (no normalise)
//   4. Build 16-feature vector (FEATURE_ORDER from config.py)
//   5. Drop R_Yaw(idx7) and L_Yaw(idx15) → 14 features
//   6. Z-score each of the 14 channels across 60-frame window
//   7. Run model → 10-class softmax
//   8. Stabilise: confidence>=0.85, same class x3, 1.5s cooldown
// =============================================================
// CHANGES v6 vs v5:
//   [FIX-E] Calibration loaded from calibration_data.h on boot.
//           firmware cal_open/cal_close used min()/max() to set
//           cal_min/cal_max, which INVERTED the normalization
//           direction for any sensor where the open hand gives a
//           higher ADC reading than the closed hand.
//           For this glove: R_Thumb, R_Index, R_Middle, L_Ring
//           were all inverted. The model sees open=1.0 but was
//           trained on open=0.0 for those channels.
//           Fix: calibration_data.h uses open=cal_min, close=cal_max
//           directly from the Python JSON, preserving true direction.
//           norm_finger() already handles negative range correctly.
//
//   [FIX-F] cal_open/cal_close commands fixed (kept as optional
//           override): no longer uses min()/max() — now correctly
//           stores open snap as cal_min and close snap as cal_max.
//           Range check now uses fabsf() to handle inverted sensors.
//
//   [CARRIED] FIX-C: EMA applied to all 16 channels including IMU
//   [CARRIED] FIX-D: EMA sentinel changed to EMA_UNINIT (-9999)
//
// REQUIRED FILES in the same folder as this .ino:
//   model_data.h         — float32 TFLite model (from Colab, ~97 KB)
//   calibration_data.h   — from gen_cal_header.py (run after calibrating)
//
// WORKFLOW (after any change to calibration):
//   1. python3 main.py  →  calibrate in Dataset Studio
//   2. python3 gen_cal_header.py --profile "Your Profile"
//   3. Copy calibration_data.h to this firmware folder
//   4. Compile and flash
// =============================================================

#include <esp_now.h>
#include <WiFi.h>
#include <WebServer.h>
#include <Wire.h>
#include <esp_mac.h>
#include <esp_wifi.h>
#include <math.h>
#include <TensorFlowLite_ESP32.h>
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_error_reporter.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "model_data.h"
#include "calibration_data.h"   // ← generated by gen_cal_header.py

// ── pins ──────────────────────────────────────────────────────
#define PIN_THUMB   1
#define PIN_INDEX   2
#define PIN_MIDDLE  3
#define PIN_RING    4
#define PIN_LITTLE  5
#define IMU_SDA     8
#define IMU_SCL     9

// ── IMU ───────────────────────────────────────────────────────
#define MPU_ADDR   0x68
#define ACCEL_SC   16384.0f
#define GYRO_SC    131.0f
#define DT         0.033f
#define COMP_G     0.98f
#define COMP_A     0.02f

// ── pipeline constants (must match live_inference.py / config.py) ──
#define EMA_ALPHA          0.25f
#define EMA_UNINIT         -9999.0f  // sentinel: outside ADC (0-4095) AND IMU (-180..180)
#define WINDOW_SIZE        60
#define NUM_RAW            16        // all sensor channels
#define NUM_FEAT           14        // after dropping R_Yaw(7) and L_Yaw(15)
#define NUM_CLASS          10
#define STRIDE             5         // run inference every N frames (~6/sec at 30 Hz)
#define CONF_THRESH        0.85f
#define DEBOUNCE           3
#define COOLDOWN_MS        1500
#define SETTLE_FRAMES      50
#define SAMPLE_MS          33        // 30 Hz loop period

// ── KEEP: indices to keep after dropping yaw channels ────────
// Matches FEATURE_IDX = [0,1,2,3,4,5,6,8,9,10,11,12,13,14] in notebook
static const int KEEP[NUM_FEAT] = {
    0,1,2,3,4,5,6,       // R_Thumb, R_Index, R_Middle, R_Ring, R_Little, R_Pitch, R_Roll
    8,9,10,11,12,13,14   // L_Thumb, L_Index, L_Middle, L_Ring, L_Little, L_Pitch, L_Roll
};

// ── gesture labels — must match label_map.json index order ────
// Generated from config.py GESTURE_LABELS order (do not change)
const char* LABEL[NUM_CLASS] = {
    "HELLO","STOP","YES","NO","THANKYOU",
    "SORRY","HELP","WATER","PLEASE","MORE"
};

// ── TFLite ────────────────────────────────────────────────────
#define ARENA_SIZE (100*1024)
uint8_t* arena = nullptr;
const tflite::Model*      tfl_model  = nullptr;
tflite::MicroInterpreter* tfl_interp = nullptr;
TfLiteTensor *tfl_in = nullptr, *tfl_out = nullptr;

// ── sliding window ────────────────────────────────────────────
float win[WINDOW_SIZE][NUM_RAW];
int   win_idx = 0, win_fill = 0, stride_ctr = 0;

// ── IMU state ─────────────────────────────────────────────────
float imu_p=0, imu_r=0, imu_y=0;
bool  imu_ok = false;

// ── EMA state: 16 channels ────────────────────────────────────
// [0-4] : R fingers, [5-9] : L fingers
// [10-12]: R IMU (pitch, roll, yaw), [13-15]: L IMU (pitch, roll, yaw)
float ema[16];

// ── calibration ───────────────────────────────────────────────
// cal_min = open hand ADC value    (normalizes to 0.0)
// cal_max = closed hand ADC value  (normalizes to 1.0)
//
// For sensors where open > close, cal_min > cal_max (negative range).
// norm_finger() handles this correctly — negative range is intentional.
// norm_finger formula: v = clamp((val - cal_min) / (cal_max - cal_min), 0, 1)
//   open:  v = (cal_min - cal_min) / range = 0.0  ✓
//   close: v = (cal_max - cal_min) / range = 1.0  ✓  (works even when range < 0)
float cal_min[10], cal_max[10];
float cal_open_snap[10];
bool  cal_open_done = false;
bool  cal_ready     = false;
bool  cal_from_file = false;  // true when loaded from calibration_data.h

// ── stabilisation ─────────────────────────────────────────────
int   last_class     = -1;
int   deb_cnt        = 0;
unsigned long last_accept_ms = 0;
unsigned long total_infer    = 0;
float last_ms = 0;

// ── ESP-NOW slave ─────────────────────────────────────────────
typedef struct { int thumb,index,middle,ring,little; float p,r,y; } Slave;
volatile Slave sv;
volatile bool  sv_new = false;
volatile unsigned long sv_ms   = 0;
volatile unsigned long sv_pkts = 0;
Slave sv_snap = {2048,2048,2048,2048,2048, 0,0,0};

// ── web server ────────────────────────────────────────────────
WebServer http(80);
String    pred_word = "";
unsigned long pred_seq = 0;

// =============================================================
// EMA FILTER
// Sentinel EMA_UNINIT: initialise to raw on first call.
// -9999 is safely outside ADC (0-4095) AND IMU (-180..180).
// =============================================================
float ema_f(float* s, float raw){
    if(*s < -9000.0f) *s = raw;
    else *s = EMA_ALPHA*raw + (1.0f - EMA_ALPHA)**s;
    return *s;
}

// =============================================================
// NORMALISE FINGER 0-1
// Matches live_inference.py _normalize() exactly:
//   norm = clamp((ema_val - cal_min) / (cal_max - cal_min), 0, 1)
//
// NEGATIVE RANGE is handled correctly and intentionally:
//   Some sensors give higher ADC when open than closed.
//   In that case cal_min > cal_max → range is negative.
//   Formula still gives: open→0.0, close→1.0 ✓
//   The clamp deals with any values outside [0,1].
// =============================================================
float norm_finger(int ch, float ema_val){
    float range = cal_max[ch] - cal_min[ch];
    // fabsf: handles both positive and negative range
    if(!cal_ready || fabsf(range) < 1.0f) return ema_val / 4095.0f;
    float v = (ema_val - cal_min[ch]) / range;
    if(v < 0.0f) v = 0.0f;
    if(v > 1.0f) v = 1.0f;
    return v;
}

// =============================================================
// IMU
// =============================================================
void imu_wr(uint8_t r, uint8_t v){
    Wire.beginTransmission(MPU_ADDR); Wire.write(r); Wire.write(v);
    Wire.endTransmission(true);
}
bool imu_init(){
    imu_wr(0x6B,0); delay(100);
    imu_wr(0x19,7); imu_wr(0x1A,3); imu_wr(0x1B,0); imu_wr(0x1C,0);
    Wire.beginTransmission(MPU_ADDR); Wire.write(0x75); Wire.endTransmission(false);
    Wire.requestFrom(MPU_ADDR,1,true);
    return Wire.available() && Wire.read()==0x68;
}
void imu_update(){
    Wire.beginTransmission(MPU_ADDR); Wire.write(0x3B); Wire.endTransmission(false);
    Wire.requestFrom(MPU_ADDR,14,true);
    auto rd=[&](){ return (int16_t)((Wire.read()<<8)|Wire.read()); };
    float ax=rd()/ACCEL_SC, ay=rd()/ACCEL_SC, az=rd()/ACCEL_SC;
    Wire.read(); Wire.read();
    float gx=rd()/GYRO_SC, gy=rd()/GYRO_SC, gz=rd()/GYRO_SC;
    float pa = atan2f(ax, sqrtf(ay*ay+az*az)) * 180.0f/(float)PI;
    float ra = atan2f(-ay, az) * 180.0f/(float)PI;
    imu_p = COMP_G*(imu_p + gx*DT) + COMP_A*pa;
    imu_r = COMP_G*(imu_r + gy*DT) + COMP_A*ra;
    imu_y += gz*DT;
    if(imu_y >  180.0f) imu_y -= 360.0f;
    if(imu_y < -180.0f) imu_y += 360.0f;
}

// =============================================================
// ESP-NOW CALLBACK
// =============================================================
void on_slave(const uint8_t* mac, const uint8_t* data, int len){
    if(len == sizeof(Slave)){
        memcpy((void*)&sv, data, sizeof(Slave));
        sv_new = true; sv_ms = millis(); sv_pkts++;
    }
}

// =============================================================
// WINDOW APPEND
// =============================================================
void win_append(const float* f){
    for(int i=0;i<NUM_RAW;i++) win[win_idx][i] = f[i];
    win_idx = (win_idx+1) % WINDOW_SIZE;
    if(win_fill < WINDOW_SIZE) win_fill++;
}

// =============================================================
// Z-SCORE PREPROCESSING
// Matches preprocess() in notebook Section 3 exactly.
// Handles static poses (tiny std) with a 1e-6 floor on std.
// =============================================================
void build_tensor(){
    int start = win_idx;

    float mean[NUM_FEAT] = {};
    for(int t=0; t<WINDOW_SIZE; t++){
        int i=(start+t)%WINDOW_SIZE;
        for(int k=0;k<NUM_FEAT;k++) mean[k]+=win[i][KEEP[k]];
    }
    for(int k=0;k<NUM_FEAT;k++) mean[k]/=WINDOW_SIZE;

    float var[NUM_FEAT] = {};
    for(int t=0; t<WINDOW_SIZE; t++){
        int i=(start+t)%WINDOW_SIZE;
        for(int k=0;k<NUM_FEAT;k++){float d=win[i][KEEP[k]]-mean[k];var[k]+=d*d;}
    }
    float sd[NUM_FEAT];
    for(int k=0;k<NUM_FEAT;k++){
        sd[k]=sqrtf(var[k]/WINDOW_SIZE);
        if(sd[k]<1e-6f) sd[k]=1e-6f;
    }

    float* dst=tfl_in->data.f;
    for(int t=0; t<WINDOW_SIZE; t++){
        int i=(start+t)%WINDOW_SIZE;
        for(int k=0;k<NUM_FEAT;k++) *dst++=(win[i][KEEP[k]]-mean[k])/sd[k];
    }
}

// =============================================================
// INFERENCE
// =============================================================
int do_inference(float* conf_out){
    build_tensor();
    unsigned long t0=micros();
    if(tfl_interp->Invoke()!=kTfLiteOk){Serial.println("[ERR] Invoke");return -1;}
    last_ms=(micros()-t0)/1000.0f; total_infer++;
    float* o=tfl_out->data.f;
    int best=0; float bv=o[0];
    for(int i=1;i<NUM_CLASS;i++) if(o[i]>bv){bv=o[i];best=i;}
    *conf_out=bv; return best;
}

// =============================================================
// STABILISATION
// =============================================================
bool stabilise(int cls, float conf, int* accepted){
    if(conf<CONF_THRESH) return false;
    if(last_accept_ms>0&&(millis()-last_accept_ms)<COOLDOWN_MS) return false;
    if(cls==last_class) deb_cnt++;
    else{ deb_cnt=1; last_class=cls; }
    if(deb_cnt>=DEBOUNCE){
        *accepted=cls; deb_cnt=0; last_accept_ms=millis(); return true;
    }
    return false;
}

// =============================================================
// RESET EMA (called after calibration change or on recal)
// =============================================================
void reset_ema(){
    for(int i=0;i<16;i++) ema[i]=EMA_UNINIT;
}

// =============================================================
// WEB PAGE
// =============================================================
const char PAGE[] PROGMEM = R"HTML(<!DOCTYPE html><html><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Smart Glove</title>
<style>body{font-family:system-ui;background:#111;color:#eee;display:flex;
flex-direction:column;align-items:center;padding:20px}
.st{padding:5px 12px;border-radius:20px;font-size:13px;margin:8px}
.on{background:#1a4a1a;color:#6f6}.off{background:#4a1a1a;color:#f66}
.btn{padding:14px 28px;background:#2255cc;color:#fff;border:none;
border-radius:8px;font-size:16px;cursor:pointer;margin:16px}
.btn.h{display:none}
.word{font-size:72px;font-weight:900;padding:20px 40px;background:#1a1a1a;
border-radius:12px;min-width:220px;text-align:center;margin:20px;
transition:background .15s}
.word.p{background:#1a2a4a}
.hist{width:100%;max-width:400px}
.hi{padding:8px 14px;margin:3px 0;background:#1e1e1e;border-radius:6px}
.mute{padding:10px 20px;background:#333;border:none;color:#eee;
border-radius:6px;cursor:pointer;margin-top:16px}
.mute.off{background:#4a1a1a}</style></head><body>
<h2>Smart Glove — ISL</h2>
<div id="st" class="st off">Connecting...</div>
<button id="eb" class="btn" onclick="en()">Tap to enable speech</button>
<div id="w" class="word">—</div>
<div class="hist" id="h"></div>
<button id="mb" class="mute" onclick="tog()">Speech ON</button>
<script>
var ok=false,on=false,hist=[],seq=-1;
function en(){var u=new SpeechSynthesisUtterance(' ');u.volume=0;
speechSynthesis.speak(u);ok=true;on=true;
document.getElementById('eb').className='btn h';
document.getElementById('mb').textContent='Speech ON'}
function tog(){if(!ok){en();return}on=!on;var b=document.getElementById('mb');
b.textContent=on?'Speech ON':'Speech OFF';b.className=on?'mute':'mute off'}
function say(w){if(!ok||!on)return;var u=new SpeechSynthesisUtterance(w);
u.lang='en-IN';speechSynthesis.speak(u)}
function show(w){var el=document.getElementById('w');el.textContent=w;
el.className='word p';setTimeout(()=>el.className='word',300);say(w);
hist.unshift(w);if(hist.length>6)hist.pop();
document.getElementById('h').innerHTML=hist.map(x=>'<div class="hi">'+x+'</div>').join('')}
function poll(){fetch('/poll').then(r=>r.json()).then(d=>{
var s=document.getElementById('st');s.textContent='Connected';s.className='st on';
if(seq<0)seq=d.seq;else if(d.seq>seq){seq=d.seq;show(d.word)}
}).catch(()=>{var s=document.getElementById('st');s.textContent='No connection';
s.className='st off'}).finally(()=>setTimeout(poll,200))}
poll();</script></body></html>)HTML";

void http_root(){ http.send_P(200,"text/html",PAGE); }
void http_poll(){
    char j[80];
    snprintf(j,80,"{\"seq\":%lu,\"word\":\"%s\"}",pred_seq,pred_word.c_str());
    http.send(200,"application/json",j);
}

// =============================================================
// SERIAL COMMANDS
//   cal_show  — print current calibration (from header file or override)
//   cal_open  — OPTIONAL: override calibration manually (open hands)
//   cal_close — OPTIONAL: override calibration manually (close fists)
//   stats     — print inference counters
//   help      — list commands
// =============================================================
void handle_serial(){
    if(!Serial.available()) return;
    String cmd=Serial.readStringUntil('\n'); cmd.trim();

    if(cmd=="cal_open"){
        // Optional manual override — captures open hand snapshot
        delay(300);  // 300ms to let EMA converge after repositioning
        for(int i=0;i<5;i++) cal_open_snap[i]   = ema[i];
        for(int i=0;i<5;i++) cal_open_snap[5+i] = ema[5+i];
        cal_open_done=true;
        Serial.println("\n  [CAL] Step 1 done — open-hand snapshot captured.");
        Serial.println("  Now close BOTH fists tightly, then type: cal_close\n");
    }
    else if(cmd=="cal_close"){
        if(!cal_open_done){ Serial.println("  [CAL] Run cal_open first."); return; }
        delay(300);
        float close_v[10];
        for(int i=0;i<5;i++) close_v[i]   = ema[i];
        for(int i=0;i<5;i++) close_v[5+i] = ema[5+i];
        bool ok2=true;
        for(int i=0;i<10;i++){
            // Store open as cal_min and close as cal_max — preserves direction.
            // Do NOT use min()/max() here: that would invert sensors where open>close.
            cal_min[i] = cal_open_snap[i];
            cal_max[i] = close_v[i];
            if(fabsf(cal_max[i]-cal_min[i]) < 30) ok2=false;
        }
        if(ok2){
            cal_ready=true; cal_open_done=false; cal_from_file=false;
            win_fill=0; win_idx=0; stride_ctr=0;
            last_class=-1; deb_cnt=0;
            memset(win,0,sizeof(win));
            Serial.println("\n  ================================");
            Serial.println("   MANUAL CALIBRATION DONE");
            Serial.println("   (calibration_data.h overridden)");
            Serial.println("  ================================\n");
        } else {
            Serial.println("  [CAL] FAIL — fingers not moving enough.");
            Serial.println("  Ensure magnets are correctly positioned.");
            Serial.println("  Redo: cal_open → cal_close\n");
        }
    }
    else if(cmd=="cal_show"){
        const char* n[]={"R_Thumb","R_Index","R_Middle","R_Ring","R_Little",
                         "L_Thumb","L_Index","L_Middle","L_Ring","L_Little"};
        Serial.println();
        if(cal_from_file) Serial.println("  Calibration source: calibration_data.h");
        else              Serial.println("  Calibration source: manual override");
        Serial.print("  Status: "); Serial.println(cal_ready?"ACTIVE":"NOT DONE");
        for(int i=0;i<10;i++){
            float range=cal_max[i]-cal_min[i];
            Serial.printf("  %-9s  open=%.0f  close=%.0f  range=%.0f%s\n",
                n[i], cal_min[i], cal_max[i], fabsf(range),
                range<0?" (inverted sensor — normal)":"");
        }
        Serial.println();
    }
    else if(cmd=="stats"){
        Serial.printf("  inferences=%lu  last_ms=%.1f  accepted=%lu  slave_pkts=%lu\n",
            total_infer,last_ms,pred_seq,sv_pkts);
    }
    else if(cmd=="help"){
        Serial.println("  cal_show  — print current calibration values");
        Serial.println("  cal_open  — optional manual override (open hands first)");
        Serial.println("  cal_close — optional manual override (close fists)");
        Serial.println("  stats     — inference and packet counters");
    }
}

// =============================================================
// SETUP
// =============================================================
void setup(){
    Serial.begin(115200); delay(2000);

    // Initialise all EMA slots to sentinel
    reset_ema();

    // Allocate TFLite arena (prefer PSRAM, fall back to internal SRAM)
    arena=(uint8_t*)heap_caps_aligned_alloc(16,ARENA_SIZE,MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT);
    if(!arena) arena=(uint8_t*)heap_caps_aligned_alloc(16,ARENA_SIZE,MALLOC_CAP_INTERNAL|MALLOC_CAP_8BIT);
    if(!arena){Serial.println("FATAL: arena alloc failed");while(1)delay(100);}

    Serial.println("\n================================");
    Serial.println(" Smart Glove — Master Inference");
    Serial.println("================================");

    // ADC + IMU
    analogReadResolution(12);
    analogSetAttenuation(ADC_11db);
    Wire.begin(IMU_SDA,IMU_SCL);
    Wire.setClock(400000);
    imu_ok=imu_init();
    Serial.print("[IMU] "); Serial.println(imu_ok?"OK":"FAIL");
    if(imu_ok){
        for(int i=0;i<SETTLE_FRAMES;i++){imu_update();delay(SAMPLE_MS);}
        imu_y=0;
        Serial.println("[IMU] Settled");
    }

    // WiFi SoftAP
    WiFi.mode(WIFI_AP_STA);
    WiFi.softAP("SmartGlove","",1);
    Serial.print("[WiFi] SmartGlove @ "); Serial.println(WiFi.softAPIP());

    // HTTP
    http.on("/",http_root); http.on("/poll",http_poll); http.begin();
    Serial.println("[HTTP] Ready");

    // ESP-NOW
    delay(200); esp_wifi_set_ps(WIFI_PS_NONE);
    if(esp_now_init()==ESP_OK){
        delay(50); esp_now_register_recv_cb(on_slave);
        Serial.println("[ESP-NOW] OK");
    } else {
        Serial.println("[ESP-NOW] FAIL");
    }

    // TFLite
    tfl_model=tflite::GetModel(g_model);
    static tflite::AllOpsResolver res;
    static tflite::MicroErrorReporter rep;
    static tflite::MicroInterpreter interp(tfl_model,res,arena,ARENA_SIZE,&rep);
    tfl_interp=&interp;
    if(tfl_interp->AllocateTensors()!=kTfLiteOk){
        Serial.println("[TFL] FAIL AllocateTensors");
        while(1)delay(100);
    }
    tfl_in=tfl_interp->input(0); tfl_out=tfl_interp->output(0);
    Serial.printf("[TFL] OK  Input 1x%dx%d  Output 1x%d\n",
        tfl_in->dims->data[1],tfl_in->dims->data[2],tfl_out->dims->data[1]);

    // ── Load calibration from calibration_data.h ─────────────────
    // This uses the exact same calibration as live_inference.py,
    // ensuring open→0.0 and close→1.0 on ALL channels regardless
    // of whether a sensor produces higher ADC when open or closed.
    for(int i=0;i<10;i++){
        cal_min[i]=CAL_MIN_DATA[i];
        cal_max[i]=CAL_MAX_DATA[i];
    }
    cal_ready=true;
    cal_from_file=true;

    Serial.println("[CAL] Loaded from calibration_data.h");
    Serial.println("      Type 'cal_show' to verify values");
    Serial.println();
    Serial.println("================================");
    Serial.println(" READY — waiting for left glove ");
    Serial.println("================================");
    Serial.println();
}

// =============================================================
// LOOP — 30 Hz
// =============================================================
unsigned long last_t=0;
int frame_id=0;

void loop(){
    http.handleClient();
    handle_serial();

    unsigned long now=millis();
    if(now-last_t<SAMPLE_MS) return;
    last_t=now;

    // 1. Read right-hand sensors
    int rt=analogRead(PIN_THUMB),  ri=analogRead(PIN_INDEX),
        rm=analogRead(PIN_MIDDLE), rr=analogRead(PIN_RING),
        rl=analogRead(PIN_LITTLE);
    if(imu_ok) imu_update();

    // 2. Update left-hand snapshot from ESP-NOW
    bool sv_alive=(sv_ms>0)&&(millis()-sv_ms<2000);
    if(sv_alive&&sv_new){
        memcpy(&sv_snap,(void*)&sv,sizeof(Slave)); sv_new=false;
    }

    // 3. EMA filter — ALL 16 channels (matches live_inference.py)
    float ef[10];
    ef[0]=ema_f(&ema[0],rt);           ef[1]=ema_f(&ema[1],ri);
    ef[2]=ema_f(&ema[2],rm);           ef[3]=ema_f(&ema[3],rr);
    ef[4]=ema_f(&ema[4],rl);
    ef[5]=ema_f(&ema[5],sv_snap.thumb);  ef[6]=ema_f(&ema[6],sv_snap.index);
    ef[7]=ema_f(&ema[7],sv_snap.middle); ef[8]=ema_f(&ema[8],sv_snap.ring);
    ef[9]=ema_f(&ema[9],sv_snap.little);

    // 4. Build 16-feature frame
    float frame[NUM_RAW];
    for(int i=0;i<5;i++) frame[i]   = norm_finger(i, ef[i]);
    frame[5]  = ema_f(&ema[10], imu_ok?imu_p:0.0f);  // R_Pitch
    frame[6]  = ema_f(&ema[11], imu_ok?imu_r:0.0f);  // R_Roll
    frame[7]  = ema_f(&ema[12], imu_ok?imu_y:0.0f);  // R_Yaw  (dropped by KEEP)
    for(int i=0;i<5;i++) frame[8+i] = norm_finger(5+i, ef[5+i]);
    frame[13] = ema_f(&ema[13], sv_snap.p);            // L_Pitch
    frame[14] = ema_f(&ema[14], sv_snap.r);            // L_Roll
    frame[15] = ema_f(&ema[15], sv_snap.y);            // L_Yaw  (dropped by KEEP)

    win_append(frame);
    stride_ctr++;

    // Gates
    if(!cal_ready){
        if(frame_id%900==0) Serial.println("  [WAIT] cal_ready not set");
        frame_id++; return;
    }
    if(!sv_alive){
        if(frame_id%180==0) Serial.println("  [WAIT] Left glove not connected.");
        frame_id++; return;
    }
    if(win_fill<WINDOW_SIZE){ frame_id++; return; }
    if(stride_ctr<STRIDE){ frame_id++; return; }
    stride_ctr=0;

    float conf;
    int cls=do_inference(&conf);
    if(cls<0){ frame_id++; return; }

    Serial.printf("[PRED] %-10s %3.0f%%\n", LABEL[cls], conf*100);

    int accepted;
    if(stabilise(cls,conf,&accepted)){
        Serial.println();
        Serial.println("  +-------------------------------+");
        Serial.printf( "  |  >> %-10s  %5.1f%%     |\n", LABEL[accepted],conf*100);
        Serial.println("  +-------------------------------+");
        Serial.println();
        pred_word=LABEL[accepted]; pred_seq++;
    }

    frame_id++;
}
